RottenRun/Controllers/FavoriteController.cs
using DeliveryShop.Database;
using DeliveryShop.Database.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace RottenRun.Controllers;

public class FavoriteController : Controller
{
    private DBContext _context = new DBContext();
    private Users user;
    public void LoadUser()
    {
        if(Request.Cookies.ContainsKey("user"))
            user = JsonConvert.DeserializeObject<Users>(Request.Cookies["user"]);
    }
    public IActionResult Index()
    {
        LoadUser();
        if (user == null)
            return RedirectToAction("Log","Profile");
        _context.Categories.ToList();
        _context.Products.ToList();
        _context.FavoriteProducts.ToList();
        _context.Users.ToList();
        var listProducts = _context.Products.ToList();
        foreach (var product in listProducts)
        {
            if(user==null)
                break;
            if (product.FavoriteProductsList.FirstOrDefault(u=>u.User.Id==user.Id) != null)
                product.IsLike = true;
        }

        var favoritelist = listProducts.Where(p => p.IsLike).ToList();
        return View(favoritelist);
    }
    [HttpPost]
    public IActionResult AddToCart(int id)
    {
        LoadUser();
        if(user == null) 
            return RedirectToAction("Index","Profile");
        var existingProduct = _context.Products.Find(id);
        if(existingProduct == null)  
            return RedirectToAction("Index");
        _context.Baskets.ToList();
        _context.Products.ToList();
        Baskets basket = new Baskets();
        var orderUser = _context.Orders.OrderBy(o=>o.Id).LastOrDefault(o => o.User.Id == user.Id);
        if (orderUser == null) 
            orderUser = new Orders()
            {
                User = _context.Users.FirstOrDefault(u=>u.Id==user.Id), 
                Status = _context.Statuses.FirstOrDefault(s=>s.Id == 4)
            };
        foreach (var orderBasket in orderUser.BasketsList)
        {
            if(existingProduct.Id == orderBasket.Product.Id) 
                return RedirectToAction("Index");
        }
        basket.Product = existingProduct;
        basket.Count += 1;
        basket.Order = orderUser;
        _context.Baskets.Add(basket);
        TempData["TitleNotification"] = "Успешно";
        TempData["Notification"] = $"Товар {existingProduct.Name} добавлен в корзину";
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
    [HttpPost]
    public IActionResult RemoveToFavorite(int id)
    {
        LoadUser();
        _context.Products.ToList();
        _context.Users.ToList();
        if(user == null) 
            return RedirectToAction("Index","Profile");
        var existingProduct = _context.Products.Find(id);
        if(existingProduct == null)  
            return RedirectToAction("Index");
        var favoriteProduct = _context.FavoriteProducts.FirstOrDefault(f => f.User.Id == user.Id && f.Product.Id == existingProduct.Id);
        if (favoriteProduct == null) return RedirectToAction("Index");
        _context.Remove(favoriteProduct);
        _context.SaveChanges();
        TempData["TitleNotification"] = "Успешно";
        TempData["Notification"] = $"Товар {existingProduct.Name} убран из избранное";
        return RedirectToAction("Index");
    }
}

RottenRun/Controllers/OrderController.cs
using DeliveryShop.Database;
using DeliveryShop.Database.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace RottenRun.Controllers;

public class OrderController : Controller
{
    private DBContext _context = new DBContext();
    private Users user;
    public IActionResult Index()
    {
        LoadUser();
        if (user == null)
            return RedirectToAction("Log", "Profile");
        _context.Baskets.ToList();
        _context.Statuses.ToList();
        _context.Addresses.ToList();
        _context.Products.ToList();
        var orderList = _context.Orders.Where(order =>  order.User.Id == user.Id).ToList();
        foreach (var order in orderList)
        {
           order.CountPrice();
        }
        return View(orderList);
    }

    public IActionResult OpenOrder(int id)
    {
        _context.Baskets.ToList();
        _context.Products.ToList();
        _context.Addresses.ToList();
        _context.Statuses.ToList();
        var order = _context.Orders.FirstOrDefault(o => o.Id == id);
        if (order == null)
            return RedirectToAction("Index");
        return View(order);
    }

    public void LoadUser()
    {
        if(Request.Cookies.ContainsKey("user"))
            user = JsonConvert.DeserializeObject<Users>(Request.Cookies["user"]);
    }
}

RottenRun/Views/Shared/_Layout.cshtml
@using DeliveryShop.Database.Models
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Newtonsoft.Json
<!DOCTYPE html>
<html lang="en">
@{
    Users _user = null;
    if(Context.Request.Cookies.ContainsKey("user"))
        _user = JsonConvert.DeserializeObject<Users>(Context.Request.Cookies["user"]);
}
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RottenRun</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RottenRun.styles.css" asp-append-version="true"/>
    <link href="https://use.fontawesome.com/releases/v6.4.2/css/all.css" rel="stylesheet" asp-append-version="true">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet" asp-append-version="true">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
        <div class="container-fluid">
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1 header-list">
                    <img src="~/source/logo.png" width="60rem"></img>
                    <li class="nav-item" style="width: 15%">
                        <div class="nav-link d1" >
                            <input id="searchText" name="textSearch"  type="text" placeholder="Искать здесь...">
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Продукты</a>
                    </li>
                    <li class="main_c nav-item">
                    <a class="nav-link text-dark favorite-container" asp-controller="Basket" asp-action="Index">
                        <p class="mb-0">Корзина</p>
                        <i class="icon fa fa-shopping-basket fa-2x mt-0"></i>
                    </a>
                    <a class="nav-link text-dark favorite-container mt-0" asp-controller="Favorite" asp-action="Index">
                        <p class="mb-0">Избранное</p>
                        <i class="icon fa fa-heart fa-2x"></i>
                    </a>
                    <a class="nav-link text-dark favorite-container mt-0" onclick="clickProfile()">
                        <p class="mb-0">Профиль</p>
                        <i class="icon fa fa-user fa-2x"></i>
                    </a>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div id="containerProfile" class="container-profile" style="height: 80vh">
    <div class="profile-modal">
        @{
            if (_user != null)
            {
                <form class="modal-content-profile" id="contentProfile" method="get">
                    <div class="profile-info">
                        <span class="span-name" >@_user.Name</span>
                        <span class="span-email">@_user.Email</span>
                    </div>
                    <button class="btn btn-outline-secondary" type="submit" asp-action="Index" asp-controller="Profile">
                        <i class="fa fa-user">
                        </i>
                        Аккаунт
                    </button>
                    <button class="btn btn-outline-secondary" type="submit" asp-action="Index" asp-controller="Order">
                        <i class="fa fa-barcode" style="margin-right:4px ">
                        </i>Заказы
                    </button>
                    <button class="btn btn-outline-dark" type="submit" asp-action="LogOut" asp-controller="Profile">Выйти</button>
                </form>
            }
            else
            {
                <form class="modal-content-profile" id="contentProfile" method="get">
                    <button class="btn btn-outline-dark" type="submit" asp-action="Log" asp-controller="Profile">Войти</button>
                </form>
            }
        }
        
    </div>
</div>
<div class="div-notify" id="divNotify">
    <h4>@TempData["TitleNotification"]</h4>
    <span>@TempData["Notification"]</span>
</div>
<div class="container mt-3" style="height: 80vh">
    <main role="main" class="pb-3" style="height: 100%">
        @RenderBody()
    </main>
</div>
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - RottenRun
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>